version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresElectricalColumnManager
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=ElectricalColumnManager
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/ElectricalColumnManager
volumes:
  postgres_db:
    driver: local
